# Clash 订阅转换服务 - 生产环境配置
# 与现有 subconverter 系统共存配置

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 2
  reload: false

# 应用配置
app:
  name: "Clash 订阅转换服务"
  version: "1.0.0"
  description: "高性能的 Clash 代理订阅转换工具"
  prefix: "/clash/api"  # 应用路径前缀

# 缓存配置
cache:
  enabled: true
  ttl: 3600  # 1小时缓存
  max_size: 1000
  redis_url: null  # 生产环境可配置 Redis

# 规则配置
rules:
  # 默认远程配置规则
  default_remote_config: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online.ini"
  
  # 规则缓存时间（秒）
  cache_ttl: 7200  # 2小时
  
  # 支持的目标格式
  supported_targets:
    - "clash"
    - "clash-meta"
    - "surge"
    - "quantumult-x"
    - "surfboard"

# CORS 配置
cors:
  allow_origins: 
    - "https://sub.guancn.me"
    - "http://localhost:3000"
  allow_methods: 
    - "GET"
    - "POST"
    - "OPTIONS"
  allow_headers: 
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true

# 安全配置
security:
  # 速率限制
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst: 10
  
  # 请求大小限制
  max_content_length: 10485760  # 10MB
  
  # 超时设置
  timeout:
    connect: 30
    read: 60
    total: 120

# 日志配置
logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/app/logs/app.log"
  max_size: "10MB"
  backup_count: 5
  
  # 访问日志
  access_log: true
  access_log_file: "/app/logs/access.log"
  
  # 敏感信息过滤
  filter_sensitive: true

# 代理配置
proxy:
  # 支持的协议
  supported_protocols:
    - "ss"
    - "ssr"
    - "vmess"
    - "vless"
    - "trojan"
    - "hysteria"
    - "hysteria2"
    - "tuic"
    - "wireguard"
  
  # 协议端口范围检查
  port_validation: true
  port_range: [1, 65535]
  
  # 节点测试
  health_check:
    enabled: false  # 生产环境暂时禁用
    timeout: 5
    concurrency: 10

# 监控配置
monitoring:
  # 指标收集
  metrics:
    enabled: true
    endpoint: "/metrics"
  
  # 健康检查
  health:
    enabled: true
    endpoint: "/health"
    
  # 统计信息
  stats:
    enabled: true
    endpoint: "/stats"

# 第三方服务配置
external:
  # 规则源
  rule_providers:
    acl4ssr: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master"
    subconverter: "https://github.com/tindy2013/subconverter"
  
  # 地理位置数据库
  geoip:
    enabled: true
    update_interval: 86400  # 24小时更新一次
    
  # DNS 配置
  dns:
    enabled: true
    servers:
      - "8.8.8.8"
      - "1.1.1.1"

# 性能配置
performance:
  # 连接池
  connection_pool:
    max_connections: 100
    max_keepalive_connections: 20
    keepalive_expiry: 5
  
  # 内存限制
  memory_limit: "512MB"
  
  # 并发限制
  max_concurrent_requests: 50